### PR TITLE
Fix repo name

### PR DESCRIPTION
**Pull request by nlemoine**
Ideally, registering the plugin on packagist would make it easier to install.

### CODE REVIEW

**Comment by Rahe** [comment]
Great ! thank you :) @MaximeCulea ?

**Comment by MaximeCulea** [comment]
@nlemoine My bad, this was a quick copy/paste exemple from an other of our plugins.
Thank you.

**Comment by nlemoine** [comment]
No problem 😉 

@MaximeCulea Any chance you will submit it to packagist?

**Comment by MaximeCulea** [comment]
@nlemoine I didn't ever think about this while you can add github VCS or directly from wppackagist. So I believe there is no need to submit to packagist ?

**Comment by nlemoine** [comment]
My mistake, I didn't see that the plugin was registered on the WordPress repository. I'll use wppackagist!

**Pull request merged**
